BLOOD_GROUP = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-')
    )

STATE = (
        ('Abia','Abia'),
        ('Adamawa','Adamawa'),
        ('Akwa Ibom','Akwa Ibom'),
        ('Anambra','Anambra'),
        ('Bauchi','Bauchi'),
        ('Bayelsa','Bayelsa'),
        ('Benue','Benue'),
        ('Borno','Borno'),
        ('Cross River','Cross River'),
        ('Delta','Delta'),
        ('Ebonyi','Ebonyi'),
        ('Edo','Edo'),
        ('Ekiti','Ekiti'),
        ('Enugu','Enugu'),
        ('Gombe','Gombe'),
        ('Imo','Imo'),
        ('Jigawa','Jigawa'),
        ('Kaduna','Kaduna'),
        ('Kano','Kano'),
        ('Katsina','Katsina'),
        ('Kebbi','Kebbi'),
        ('Kogi','Kogi'),
        ('Kwara','Kwara'),
        ('Lagos','Lagos'),
        ('Nasarawa','Nasarawa'),
        ('Niger','Niger'),
        ('Ogun','Ogun'),
        ('Ondo','Ondo'),
        ('Osun','Osun'),
        ('Oyo','Oyo'),
        ('Plateau','Plateau'),
        ('Rivers','Rivers'),
        ('Sokoto','Sokoto'),
        ('Taraba','Taraba'),
        ('Yobe','Yobe'),
        ('Zamfara','Zamfara')
    )

BANK = (
        ('Access Bank Plc','Access Bank Plc'),
('Fidelity Bank Plc','Fidelity Bank Plc'),
('First City Monument Bank Limited','First City Monument Bank Limited'),
('First Bank of Nigeria Limited','First Bank of Nigeria Limited'),
('Guaranty Trust Holding Company Plc','Guaranty Trust Holding Company Plc'),
('Union Bank of Nigeria Plc','Union Bank of Nigeria Plc'),
('United Bank for Africa Plc','United Bank for Africa Plc'),
('Zenith Bank Plc','Zenith Bank Plc'),
('Citibank Nigeria Limited','Citibank Nigeria Limited'),
('Ecobank Nigeria','Ecobank Nigeria'),
('Heritage Bank Plc','Heritage Bank Plc'),
('Keystone Bank Limited','Keystone Bank Limited'),
('Polaris Bank Limited','Polaris Bank Limited'),
('Stanbic IBTC Bank Plc','Stanbic IBTC Bank Plc'),
('Standard Chartered','Standard Chartered'),
('Sterling Bank Plc','Sterling Bank Plc'),
('Titan Trust Bank Limited','Titan Trust Bank Limited'),
('Unity Bank Plc','Unity Bank Plc'),
('Wema Bank Plc','Wema Bank Plc'),
('Globus Bank Limited','Globus Bank Limited'),
('Parallex Bank Limited','Parallex Bank Limited'),
('Providus Bank Limited','Providus Bank Limited'),
('SunTrust Bank Nigeria Limited','SunTrust Bank Nigeria Limited'),
('Jaiz Bank Plc','Jaiz Bank Plc'),
('LOTUS BANK','LOTUS BANK'),
('TAJBank Limited','TAJBank Limited'),
('Mutual Trust Microfinance Bank','Mutual Trust Microfinance Bank'),
('Rephidim Microfinance Bank','Rephidim Microfinance Bank'),
('Shepherd Trust Microfinance Bank','Shepherd Trust Microfinance Bank'),
('Empire Trust Microfinance Bank','Empire Trust Microfinance Bank'),
('Finca Microfinance Bank Limited','Finca Microfinance Bank Limited'),
('Fina Trust Microfinance Bank','Fina Trust Microfinance Bank'),
('Accion Microfinance Bank','Accion Microfinance Bank'),
('Peace Microfinance Bank','Peace Microfinance Bank'),
('Infinity Microfinance Bank','Infinity Microfinance Bank'),
('Pearl Microfinance Bank Limited','Pearl Microfinance Bank Limited'),
('Covenant Microfinance Bank Ltd','Covenant Microfinance Bank Ltd'),
('Advans La Fayette Microfinance Bank','Advans La Fayette Microfinance Bank'),
('Sparkle Bank','Sparkle Bank'),
('Kuda Bank','Kuda Bank'),
('Rubies Bank','Rubies Bank'),
('VFD MFB','VFD MFB'),
('Mint Finex MFB','Mint Finex MFB'),
('Mkobo MFB','Mkobo MFB'),
('Coronation Merchant Bank','Coronation Merchant Bank'),
('FBNQuest Merchant Bank','FBNQuest Merchant Bank'),
('FSDH Merchant Bank','FSDH Merchant Bank'),
('Rand Merchant Bank','Rand Merchant Bank'),
('Nova Merchant Bank','Nova Merchant Bank')
    )

RELIGION = (
        ('CHRISTIANITY','CHRISTIANITY'),
        ('ISLAM','ISLAM')
    )

GENDER = (
        ('FEMALE','FEMALE'),
        ('MALE','MALE')
    )
POSITION = (
        ('STAFF','STAFF'),
    )
