# Generated by Django 4.0.5 on 2022-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'News'), ('event', 'Events'), ('gallery', 'Gallery'), ('support', 'Support')], max_length=10)),
                ('caption', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('posted_at', models.DateField()),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('home_address', models.TextField()),
                ('residential_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('religion', models.CharField(choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM')], max_length=20)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=6)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=30)),
                ('lga', models.CharField(max_length=40)),
                ('account_number', models.CharField(max_length=12)),
                ('bank_name', models.CharField(choices=[('Access Bank Plc', 'Access Bank Plc'), ('Fidelity Bank Plc', 'Fidelity Bank Plc'), ('First City Monument Bank Limited', 'First City Monument Bank Limited'), ('First Bank of Nigeria Limited', 'First Bank of Nigeria Limited'), ('Guaranty Trust Holding Company Plc', 'Guaranty Trust Holding Company Plc'), ('Union Bank of Nigeria Plc', 'Union Bank of Nigeria Plc'), ('United Bank for Africa Plc', 'United Bank for Africa Plc'), ('Zenith Bank Plc', 'Zenith Bank Plc'), ('Citibank Nigeria Limited', 'Citibank Nigeria Limited'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Heritage Bank Plc', 'Heritage Bank Plc'), ('Keystone Bank Limited', 'Keystone Bank Limited'), ('Polaris Bank Limited', 'Polaris Bank Limited'), ('Stanbic IBTC Bank Plc', 'Stanbic IBTC Bank Plc'), ('Standard Chartered', 'Standard Chartered'), ('Sterling Bank Plc', 'Sterling Bank Plc'), ('Titan Trust Bank Limited', 'Titan Trust Bank Limited'), ('Unity Bank Plc', 'Unity Bank Plc'), ('Wema Bank Plc', 'Wema Bank Plc'), ('Globus Bank Limited', 'Globus Bank Limited'), ('Parallex Bank Limited', 'Parallex Bank Limited'), ('Providus Bank Limited', 'Providus Bank Limited'), ('SunTrust Bank Nigeria Limited', 'SunTrust Bank Nigeria Limited'), ('Jaiz Bank Plc', 'Jaiz Bank Plc'), ('LOTUS BANK', 'LOTUS BANK'), ('TAJBank Limited', 'TAJBank Limited'), ('Mutual Trust Microfinance Bank', 'Mutual Trust Microfinance Bank'), ('Rephidim Microfinance Bank', 'Rephidim Microfinance Bank'), ('Shepherd Trust Microfinance Bank', 'Shepherd Trust Microfinance Bank'), ('Empire Trust Microfinance Bank', 'Empire Trust Microfinance Bank'), ('Finca Microfinance Bank Limited', 'Finca Microfinance Bank Limited'), ('Fina Trust Microfinance Bank', 'Fina Trust Microfinance Bank'), ('Accion Microfinance Bank', 'Accion Microfinance Bank'), ('Peace Microfinance Bank', 'Peace Microfinance Bank'), ('Infinity Microfinance Bank', 'Infinity Microfinance Bank'), ('Pearl Microfinance Bank Limited', 'Pearl Microfinance Bank Limited'), ('Covenant Microfinance Bank Ltd', 'Covenant Microfinance Bank Ltd'), ('Advans La Fayette Microfinance Bank', 'Advans La Fayette Microfinance Bank'), ('Sparkle Bank', 'Sparkle Bank'), ('Kuda Bank', 'Kuda Bank'), ('Rubies Bank', 'Rubies Bank'), ('VFD MFB', 'VFD MFB'), ('Mint Finex MFB', 'Mint Finex MFB'), ('Mkobo MFB', 'Mkobo MFB'), ('Coronation Merchant Bank', 'Coronation Merchant Bank'), ('FBNQuest Merchant Bank', 'FBNQuest Merchant Bank'), ('FSDH Merchant Bank', 'FSDH Merchant Bank'), ('Rand Merchant Bank', 'Rand Merchant Bank'), ('Nova Merchant Bank', 'Nova Merchant Bank')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatapp_number', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('National President', 'National President'), ('Deputy National President', 'Deputy National President'), ('National Secretary', 'National Secretary'), ('Assistant National Secretary', 'Assistant National Secretary'), ('Director of Administration', 'Director of Administration'), ('Deputy Director of Administration', 'Deputy Director of Administration'), ('National Financial Secretary', 'National Financial Secretary'), ('Assistant National Financial Secretary', 'Assistant National Financial Secretary'), ('Assistant National Financial Secretary', 'Assistant National Financial Secretary'), ('National Treasurer', 'National Treasurer'), ('Assistant National Treasurer', 'Assistant National Treasurer'), ('National Auditor', 'National Auditor'), ('Assistant National Auditor', 'Assistant National Auditor'), ('National P.R.O', 'National P.R.O'), ('Assistant National P.R.O', 'Assistant National P.R.O'), ('National Woman Leader', 'National Woman Leader'), ('Deputy National Woman Leader', 'Deputy National Woman Leader'), ('National Youth leader', 'National Youth leader'), ('Deputy Youth Leader', 'Deputy Youth Leader'), ('National Contact and mobilization Officer', 'National Contact and mobilization Officer'), ('Assistant Contact and mobilization Officer', 'Assistant Contact and mobilization Officer'), ('National Organisation', 'National Organisation'), ('Assistant National Organizing Secretary', 'Assistant National Organizing Secretary'), ('National Welfare Officer', 'National Welfare Officer'), ('Assistant National Welfare Officer', 'Assistant National Welfare Officer'), ('Provost', 'Provost'), ('Legal Adviser', 'Legal Adviser'), ('BOT Chairman', 'BOT Chairman'), ('BOT Secretary', 'BOT Secretary'), ('BOT Member', 'BOT Member'), ('Member', 'Member'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=70)),
                ('registration_number', models.CharField(max_length=15)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='uploads/signature/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='uploads/passport/')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
